name: Render & Deploy Test Report Site

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render:
    name: Install Rpackages and render report
    runs-on: windows-2025
    env:
      R_LIBS_USER: ${{ github.workspace }}/.Rlibrary
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
          r-version: '4.2.0' 

    - name: Set up Pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/*.R', '**/*.Rmd') }}
        restore-keys: |
           ${{ runner.os }}-R-
           
    - name: Install R packages
      shell: Rscript {0}
      run: |
        install.packages(c("remotes","reshape2","plyr","zoo",
        "RcppRoll","dataRetrieval","downloadthis","rvest","httr",
        "mapmisc","future","future.apply","flextable","ggplot2"))
    
    
    - name: Install terra and raster from rspatial and others
      shell: Rscript {0}
      run: |
        remotes::install_github("SwampThingPaul/AnalystHelper")
        remotes::install_github("SwampThingPaul/EVERSpatDat")
        install.packages('sf', type = "binary")
        install.packages('terra', repos = c('https://rspatial.r-universe.dev', 'https://cloud.r-project.org'))
        install.packages('raster', repos = c('https://rspatial.r-universe.dev', 'https://cloud.r-project.org'))

    - name: Render R Markdown
      run: Rscript -e 'rmarkdown::render("./test_data_report.Rmd", output_format = "html_document")'

    - name: Configure Git
      run: |
          git config user.name "SwampThingPaul"
          git config user.email "<>"
#         git config --global user.name "github-actions"
#         git config --global user.email "github-actions@github.com"

    - name: Commit and push rendered report
      run: |
        git add -A 
        git commit -m 'update report' || echo "No changes to commit"
        git pull --rebase origin master
        git push origin || echo "No changes to commit"